name: Fail Steps with Continue on Error and Loop Check

on:
  workflow_dispatch:

jobs:
  fail-steps:
    runs-on: ubuntu-latest

    steps:
      - name: Step 1 - Fail Intentionally
        id: step1
        run: exit 1
        continue-on-error: true

      - name: Step 2 - Another Failure
        id: step2
        run: nonexistent-command
        continue-on-error: true

      - name: Step 3 - Yet Another Fail
        id: step3
        run: false
        continue-on-error: true

      - name: Final Check and Fail if
