name: Fail Steps with Continue on Error and Loop Check

on:
  workflow_dispatch:

jobs:
  fail-steps:
    runs-on: ubuntu-latest

    steps:
      - name: Step 1 - Fail Intentionally
        id: step1
        run: exit 1
        continue-on-error: true

      - name: Step 2 - Another Failure
        id: step2
        run: nonexistent-command
        continue-on-error: true

      - name: Step 3 - Yet Another Fail
        id: step3
        run: false
        continue-on-error: true

      - name: Final Check and Fail if Needed
        env:
          STEP_IDS: "step1 step2 step3"
        run: |
          failed_steps=()

          for step in $STEP_IDS; do
            outcome="${{ steps[step].outcome }}"
            if [ "$outcome" != "success" ]; then
              failed_steps+=("$step")
            fi
          done

          if [ ${#failed_steps[@]} -gt 0 ]; then
            echo "The following steps failed: ${failed_steps[*]}"
            exit 1
          else
            echo "All steps succeeded"
          fi
