name: pr-validation

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
  push:
    branches-ignore:
      - main
concurrency:
  group: validation-${{ github.event_name == 'pull_request' && github.head_ref || github.ref_name }}
  cancel-in-progress: true
  
jobs:
  fail-steps:
    runs-on: ubuntu-latest

    steps:
      - name: Step 1 - Fail Intentionally
        id: step1
        run: |
          exit 0
          echo ${{ github.workflow }}-${{ github.event_name == 'pull_request' && github.head_ref || github.ref_name }}
        continue-on-error: true

      - name: Step 2 - Another Failure
        id: step2
        run: exit 0
        continue-on-error: true

      - name: Step 3 - Yet Another Fail
        id: step3
        run: exit 0
        continue-on-error: true

      - name: Final Check and Fail if Needed
        env:
          STEP_IDS: "step1 step2 step3"
          STEP1_OUTCOME: ${{ steps.step1.outcome }}
          STEP2_OUTCOME: ${{ steps.step2.outcome }}
          STEP3_OUTCOME: ${{ steps.step3.outcome }}
        run: |
          declare -A outcomes=(
            [step1]="$STEP1_OUTCOME"
            [step2]="$STEP2_OUTCOME"
            [step3]="$STEP3_OUTCOME"
          )

          failed_steps=()
          for step in $STEP_IDS; do
            if [ "${outcomes[$step]}" != "success" ]; then
             echo "$step is failed"
             echo "${outcomes[$step]}"
             failed_steps+=("$step")
             
            fi
          done

          if [ ${#failed_steps[@]} -gt 0 ]; then
            echo "❌ The following steps failed: ${failed_steps[*]}"
            sleep 30
            exit 1
          else
            echo "✅ All steps succeedded"
          fi
