name: Open and Close Notepad on Windows Runner

on:
  workflow_dispatch:

jobs:
  open-close-notepad:
    runs-on: windows-latest

    steps:
      - name: Open Notepad
        run: start-process notepad

      - name: Wait 5 seconds
        run: Start-Sleep -Seconds 5
        shell: pwsh

      - name: Close Notepad
        run: |
          $notepad = Get-Process notepad -ErrorAction SilentlyContinue
          if ($notepad) {
            $notepad.CloseMainWindow() | Out-Null
            Start-Sleep -Seconds 2
            if (!$notepad.HasExited) {
              $notepad | Stop-Process -Force
            }
          }
        shell: pwsh

      - name: Check Chrome Version
        run: '"C:\Program Files\Google\Chrome\Application\chrome.exe" --version'

